guitcollect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('guitars/index/', views.guitars_index, name='index'),
    path('guitars/<int:guitar_id>/', views.guitars_detail, name='detail'),
    path('guitars/create/', views.GuitarCreate.as_view(), name='guitars_create'),
    path('guitars/<int:pk>/update/', views.GuitarUpdate.as_view(), name='guitars_update'),
    path('guitars/<int:pk>/delete/', views.GuitarDelete.as_view(), name='guitars_delete'),
    path('guitars/<int:guitar_id>/add_stringing/', views.add_stringing, name='add_stringing'),
    path('guitars/<int:guitar_id>/assoc_accessory/<int:accessory_id>/', views.assoc_accessory, name='assoc_accessory'),
    path('guitars/<int:guitar_id>/unassoc_accessory/<int:accessory_id>/', views.unassoc_accessory, name='unassoc_accessory'),
    path('accessories/', views.AccessoryList.as_view(), name='accessories_index'),
    path('accessories/<int:pk>/', views.AccessoryDetail.as_view(), name='accessories_detail'),
    path('accessories/create/', views.AccessoryCreate.as_view(), name='accessories_create'),
    path('accessories/<int:pk>/update/', views.AccessoryUpdate.as_view(), name='accessories_update'),
    path('accessories/<int:pk>/delete/', views.AccessoryDelete.as_view(), name='accessories_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

GAUGES = (
    ('E', 'Extra-Light'),
    ('L', 'Light'),
    ('M', 'Medium'),
    ('H', 'Heavy')
)

class Accessory(models.Model):
    brand = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    accessory_type = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('accessories_detail', kwargs={'pk': self.id})

class Guitar(models.Model):
    brand = models.CharField(max_length=20)
    model = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    accessories = models.ManyToManyField(Accessory)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.brand} {self.model} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'guitar_id': self.id})


class Stringing(models.Model):
    date = models.DateField()
    brand = models.CharField(max_length=50)
    gauge = models.CharField(
        max_length=1,
        choices=GAUGES,
        default=GAUGES[1][0]
    )
    guitar = models.ForeignKey(Guitar, on_delete=models.CASCADE)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f"Changed to {self.get_gauge_display()} {self.brand} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Stringing

class StringingForm(ModelForm):
    class Meta:
        model = Stringing
        fields = ['date', 'brand', 'gauge']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Guitar, Accessory
from .forms import StringingForm
# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def guitars_index(request):
    guitars = Guitar.objects.filter(user=request.user)

    return render(request, 'guitars/index.html', { 'guitars': guitars})

@login_required
def guitars_detail(request, guitar_id):
    guitar = Guitar.objects.get(id=guitar_id)
    stringing_form = StringingForm()
    accessory_ids = guitar.accessories.all().values_list('id')
    accessories = Accessory.objects.exclude(id__in=accessory_ids)
    return render(request, 'guitars/detail.html', { 
        'guitar': guitar,
        'stringing_form': stringing_form,
        'accessories': accessories
    })

# Class-Based Views

class GuitarCreate(LoginRequiredMixin, CreateView):
    model = Guitar
    fields = ['brand', 'model', 'description']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class GuitarUpdate(LoginRequiredMixin, UpdateView):
    model = Guitar
    fields = ['brand', 'model', 'description']


class GuitarDelete(LoginRequiredMixin, DeleteView):
    model = Guitar
    success_url = '/guitars/'

@login_required
def add_stringing(request, guitar_id):
    form = StringingForm(request.POST)
    if form.is_valid():
        new_stringing = form.save(commit=False)
        new_stringing.guitar_id = guitar_id
        new_stringing.save()
    return redirect('detail', guitar_id=guitar_id)

class AccessoryList(LoginRequiredMixin, ListView):
    model = Accessory

class AccessoryDetail(LoginRequiredMixin, DetailView):
    model = Accessory

class AccessoryCreate(LoginRequiredMixin, CreateView):
    model = Accessory
    fields = '__all__'

class AccessoryUpdate(LoginRequiredMixin, UpdateView):
    model = Accessory
    fields = ['brand', 'name', 'accessory_type']

class AccessoryDelete(LoginRequiredMixin, DeleteView):
    model = Accessory
    success_url = '/accessories/'

@login_required
def assoc_accessory(request, guitar_id, accessory_id):
    guitar = Guitar.objects.get(id=guitar_id)
    guitar.accessories.add(accessory_id)
    return redirect('detail', guitar_id=guitar_id)

@login_required
def unassoc_accessory(request, guitar_id, accessory_id):
    guitar = Guitar.objects.get(id=guitar_id)
    guitar.accessories.remove(accessory_id)
    return redirect('detail', guitar_id=guitar_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid Sign Up - Try Again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About</h1>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Guitar Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body class="grey lighten-1">
    <header>
        <nav class="nav-extended grey darken-4">
            <div class="nav-wrapper">
                <a href="{% url 'home' %}" class="brand-logo right" style="font-family: 'Lobster', cursive;">GuitarCollector</a>
            </div>
            <div class="nav-content">
                <ul class="tabs tabs-transparent">
                    <li class="tab"><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li class="tab"><a href="{% url 'accessories_create' %}">Add Accessory</a></li>
                        <li class="tab"><a href="{% url 'accessories_index' %}">View All Accessories</a></li>
                        <li class="tab"><a href="{% url 'guitars_create' %}">Add Guitar</a></li>
                        <li class="tab"><a href="{% url 'index' %}">View All Guitars</a></li>
                        <li class="tab"><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                        <li class="tab"><a href="{% url 'signup' %}">Sign Up</a></li>
                        <li class="tab"><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>

main_app/templates/guitars/detail.html
{% extends 'base.html' %}

{% block content %}

<h1 class="center">Guitar Details</h1>
<div class="row center">
    <div class="col">
        <div class="card center">
            <div class="card-content">
                <span class="card-title">{{ guitar.brand }} {{ guitar.model }}</span>
                <p>Description: {{ guitar.description }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'guitars_update' guitar.id %}">Edit</a>
                <a href="{% url 'guitars_delete' guitar.id %}">Delete</a>
            </div>
        </div>
        <div class="col">
            <form action="{% url 'add_stringing' guitar.id %}" method="POST" class="center">
                {% csrf_token %}
                {{ stringing_form.as_p }}
                <br>
                <input type="submit" class="btn" value="Add String Change">
            </form>
            <br>
        </div>
        <table class="striped col">
            <thead>
                <tr>
                    <th>Date Changed</th>
                    <th>Brand</th>
                    <th>Gauge</th>
                </tr>
            </thead>
            <tbody>
                {% for stringing in guitar.stringing_set.all %}
                    <tr>
                        <td>{{ stringing.date }}</td>
                        <td>{{ stringing.brand }}</td>
                        <td>{{ stringing.get_gauge_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col">
        <h3 class="center">{{ guitar.brand }} {{ guitar.model }} Accessories</h3>
        {% if guitar.accessories.count %}
            {% for accessory in guitar.accessories.all %}
                <div class="card">
                    <div class="card-content">
                        <p>{{ accessory.brand }} {{ accessory.name }}</p>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'unassoc_accessory' guitar.id accessory.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="Remove" class="btn">
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>No Accessories</h3>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Accessories</h3>
        {% if accessories.count %}
            {% for accessory in accessories %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            {{ accessory.brand }} {{ accessory.name }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_accessory' guitar.id accessory.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

<script>

    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'mm-dd-yyyy',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_gauge');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/guitars/index.html
{% extends 'base.html' %}

{% block content %}

{% for guitar in guitars %}

    <div class="card blue-grey lighten-2">
        <a href="{% url 'detail' guitar.id %}">
            <div class="card-content indigo-text darken-4">
                <span class="card-title">{{ guitar.brand }} {{ guitar.model }}</span>
                <p>Description: {{ guitar.description }}</p>
            </div>
        </a>
    </div>

{% endfor%}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/accessory_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Accessory</h1>

  <h4>Are you sure you want to delete <span class="red-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
    <a href="{% url 'accessories_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/accessory_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ accessory.name }}</span>
        <p>Brand: {{ accessory.brand }}</p>
        <p>Description: {{ accessory.accessory_type }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'accessories_update' accessory.id %}">Edit</a>
        <a href="{% url 'accessories_delete' accessory.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/accessory_form.html
{% extends 'base.html' %}

{% block content %}

    {% if object %}
        <h1>Edit <span class="blue-text darken-4">{{ object.name }}</span></h1>
    {% else %}
        <h1>Add Accessory</h1>
    {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            <table class="grey lighten-3">
                {{ form.as_table }}
            </table>
            <input type="submit" value="Save" class="btn">
        </form>

{% endblock %}

main_app/templates/main_app/accessory_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Accessories</h1>
{% for accessory in accessory_list %}
    <a href="{% url 'accessories_detail' accessory.id %}">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ accessory.name }}</span>
                <p>Brand: {{ accessory.brand }}</p>
                <p>Description: {{ accessory.accessory_type }}</p>
            </div>
        </div>
    </a>
{% endfor %}
{% endblock %}

main_app/templates/main_app/guitar_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Guitar</h1>

<h4>Are you sure you want to delete <span class="red-text">{{ object.brand }} {{ object.model }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
    <a href="{% url 'detail' guitar.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/guitar_form.html
{% extends 'base.html' %}

{% block content %}

    {% if object %}
        <h1>Edit <span class="blue-text darken-4">{{ object.name }}</span></h1>
    {% else %}
        <h1>Add Guitar</h1>
    {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            <table class="grey lighten-3">
                {{ form.as_table }}
            </table>
            <input type="submit" value="Save" class="btn">
        </form>

{% endblock %}